name: avoid_non_null_assertion_operator
description: A custom lint package to forbid the non-null assertion operator (!).
version: 1.7.0
repository: https://github.com/polemius/avoid_non_null_assertion_operator

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  analyzer: ^6.7.0
  custom_lint: ^0.6.8
  custom_lint_builder: ^0.6.8